language: php
sudo: false
git:
  depth: 1
env:
  global:
  - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --optimize-autoloader"
  - REPORT_TESTS_COVERAGE=0
matrix:
  fast_finish: true
  include:
  - php: 7.0
  - php: 7.1
    env: REPORT_TESTS_COVERAGE=1
cache:
  directories:
  - "$HOME/.composer/cache"
before_install:
  - travis_retry composer update
install:
  - travis_retry composer install
  - composer info -D | sort
script:
  - vendor/bin/phpunit
after_success:
  #- if [ $REPORT_TESTS_COVERAGE == 1 ]; then php vendor/bin/test-reporter --coverage-report=./tests/storage/logs/test-reports/clover.xml; fi
  - if [ $REPORT_TESTS_COVERAGE == 1 ]; then php vendor/bin/coveralls -v; fi
#addons:
#  code_climate:
#    repo_token: CODECLIMATE_REPO_TOKEN
notifications:
  email: true